name: Comment & Doc

#Fire only when a commit to main touches a .py file in samples/
on:
  push:
    branches: [main]
    paths:
      - 'samples/**/*.py'

jobs:

  comment-samples:
  #skip if this commit was made by the AI Comment Assistant
    if: ${{ !contains(github.event.head_commit.message, '[skip comment]') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write #allows committing/pushing back
      pull-requests: write #allows creating PRs
    
    steps:
      # 1 Checkout the repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Azure login (OIDC)
        uses: azure/login@v1
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: "tools/requirements.txt"

      - name: Install dependencies
        run: pip install -r tools/requirements.txt


      - name: Build list of changed samples
        run: |
          git diff --name-only ${{ github.sha }} ${{ github.sha }}^ \
          -- ':(glob)samples/**/*.py' > /tmp/updated_files.txt
          echo "Files to comment:" 
          cat /tmp/updated_files.txt


      - name: Run AI commenting script
        run: python tools/generate_comments_AOAI.py /tmp/updated_files.txt .
        env:
          AZURE_OPENAI_ENDPOINT:        ${{ vars.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}
          AZURE_TENANT_ID:              ${{ vars.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID:              ${{ vars.AZURE_CLIENT_ID }}

      - name: Create or update bot PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/auto-comment
          title: 'Add inline comments via AI assistant'
          body: 'This PR was created by the AI Comment Assistant.'
          commit-message: 'Add inline comments via AI assistant [skip comment]'
          delete-branch: true

